
theme: minima
title: Rizwan Shafiq's Coding Journey  
author: Rizwan Shafiq  
description: Exploring web development, ethical hacking, AI, and more as a passionate CS student and lifelong learner.

sass:
  style: compressed

assets:
  - css/style.css


header_links:
  - title: "About Me"
    url: /about/
  - title: "My Blogs"
    url: /blog/
  - title: "My Projects"
    url: /projects/
